baseurl = "/"
languageCode = "en-us"
title = "lolR Pro"
theme = "semantic-theme"
#googleAnalytics = "UA-114717666-1"
#disqusShortname = "systats"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"